### ISSUE TITLE
This repo is a 'tourist trap'!

### ISSUE THREAD

**Issue by marekkowalczyk** [larsschenk/ActiveBarcodeCLI#1]
Please have the decency to mention that barcodes will come out stamped with DEMO.

![ean](https://user-images.githubusercontent.com/4373765/95387778-82d3ef00-08f1-11eb-85af-a6bf0da64e79.png)

**Comment by larsschenk** [comment]
Yes, as documented. This is expected behaviour.
Please read:
https://www.activebarcode.com/commandline/bash.html

> You can try out and evaluate the REST API by omitting the API key. Without the access key, the barcode will be branded with a notice: "For evaluation use only".
